spring.application.name=backend
spring.datasource.url=mysql://root:ZMcftCcDOEYFyKYOwDeJeYoBgTsRIKHt@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=ZMcftCcDOEYFyKYOwDeJeYoBgTsRIKHt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
file.upload-dir=uploads/
server.port=${PORT:8080}